### PR TITLE
Caroleaux design creation

### PR DESCRIPTION
**Pull request by carollas**
This is a stylized website based on the design developed by ABSphreak and with an original design by Ildiko Gaspar.

### CODE REVIEW

**Comment by ABSphreak** [comment]
Hey @carolladss 
there's no way to check & verify what you've implemented.

Also, you've created a folder inside of `03domainLandingSite`
Please make your contribution separate by creating a folder `04caroleaux`
on the root of the repo and put your code there following `00template` folder structure
Your assets are also all over the place. 

Please follow the latest guidelines from #1 and be sure to include
screenshots of your work & host your fork on `gh-pages` (instructions coming soon)

Please make these changes & I will try to merge.

**Comment by carollas** [comment]
Hello, ABSphreak. I'm sorry for doing the wrong things, I'm not used to doing PR in repositories that I don't know (actually it's my first time kkkk). I hope that everything is fine now.

**Comment by ABSphreak** [comment]
@carolladss it's okay! I will fix your mistakes. Thanks for contributing 👍 
Welcome to OpenSource⚡

**Comment by ABSphreak** [comment]
I have accepted your contribution but had to delete the design as it had inaccessible design language & and it was based on another design in the repository, so it was kind of redundant. Please keep these points in mind on your next PR.

Thanks for your contribution.

**Comment by carollas** [comment]
Thanks for the tips, really! I will study a little more.

**Pull request merged**
